/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TDI;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author JoshuaOrmachea
 */
public class MDI_TDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI_TDI
     */
    public MDI_TDI() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
        
        pic1.setImagen("java.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        pic1 = new PanelImage();
        pic2 = new PanelImage();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_Ampliacion_Al_Doble_simple = new javax.swing.JMenuItem();
        jMenuItem_Ampliacion_A_Cualquier_Factor = new javax.swing.JMenuItem();
        jMenuItem_Ampliacion_Al_Doble_Con_Promedio = new javax.swing.JMenuItem();
        jMenuItem_Reduccion_A_La_Mitad_Simple = new javax.swing.JMenuItem();
        jMenuItem_Reduccion_A_Cualquier_Factor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRATAMIENTO DIGITAL DE IMAGENES");

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout pic1Layout = new javax.swing.GroupLayout(pic1);
        pic1.setLayout(pic1Layout);
        pic1Layout.setHorizontalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic1Layout.setVerticalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pic2Layout = new javax.swing.GroupLayout(pic2);
        pic2.setLayout(pic2Layout);
        pic2Layout.setHorizontalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic2Layout.setVerticalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(858, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(579, Short.MAX_VALUE))
        );

        desktopPane.add(jInternalFrame1);
        jInternalFrame1.setBounds(10, 10, 990, 670);

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setTitle("BRILLO");
        jInternalFrame2.setVisible(true);

        jSlider1.setMinimum(-100);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider1MouseClicked(evt);
            }
        });

        jLabel1.setText("0");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        desktopPane.add(jInternalFrame2);
        jInternalFrame2.setBounds(1010, 10, 190, 110);

        jInternalFrame3.setTitle("CONTRASTE");
        jInternalFrame3.setVisible(true);

        jLabel2.setText("CONTASTE");

        jButton3.setText("CONTRASTE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("ALFA");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        desktopPane.add(jInternalFrame3);
        jInternalFrame3.setBounds(1010, 130, 190, 140);

        jInternalFrame4.setTitle("GAMMA");
        jInternalFrame4.setVisible(true);

        jLabel4.setText("LAMBDA");

        jButton4.setText("GAMMA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jInternalFrame4);
        jInternalFrame4.setBounds(1010, 280, 190, 110);

        jMenu1.setText("IMAGEN");

        jMenuItem1.setText("ABRIR");
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        jMenu2.setText("OPERACIONES BASICAS");

        jMenuItem2.setText("COPIAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("GRISES");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("BRILLO");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("CONTRASTE");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("NEGATIVO");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("GAMMA");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("UMBRAL");
        jMenu2.add(jMenuItem8);

        menuBar.add(jMenu2);

        jMenu3.setText("OPERAC. GEOMETRICAS");

        jMenu4.setText("CAMBIOS DE TAMAÑO");

        jMenuItem_Ampliacion_Al_Doble_simple.setText("AMPLIACION AL DOBLE SIMPLE");
        jMenuItem_Ampliacion_Al_Doble_simple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Ampliacion_Al_Doble_simpleActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Ampliacion_Al_Doble_simple);

        jMenuItem_Ampliacion_A_Cualquier_Factor.setText("AMPLIACION A CUALQUIER FACTOR");
        jMenuItem_Ampliacion_A_Cualquier_Factor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Ampliacion_A_Cualquier_FactorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Ampliacion_A_Cualquier_Factor);

        jMenuItem_Ampliacion_Al_Doble_Con_Promedio.setText("AMPLIACION AL DOBLE CON PROMEDIO");
        jMenuItem_Ampliacion_Al_Doble_Con_Promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Ampliacion_Al_Doble_Con_PromedioActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Ampliacion_Al_Doble_Con_Promedio);

        jMenuItem_Reduccion_A_La_Mitad_Simple.setText("REDUCCION  A LA MITAD SIMPLE");
        jMenuItem_Reduccion_A_La_Mitad_Simple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Reduccion_A_La_Mitad_SimpleActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Reduccion_A_La_Mitad_Simple);

        jMenuItem_Reduccion_A_Cualquier_Factor.setText("REDUCCION A CUALQUIER FACTOR");
        jMenuItem_Reduccion_A_Cualquier_Factor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Reduccion_A_Cualquier_FactorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_Reduccion_A_Cualquier_Factor);

        jMenu3.add(jMenu4);

        jMenu5.setText("ROTACIONES");
        jMenu3.add(jMenu5);

        jMenu6.setText("OTRAS OPERACIONES");
        jMenu3.add(jMenu6);

        menuBar.add(jMenu3);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1227, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItem_Ampliacion_Al_Doble_simpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Ampliacion_Al_Doble_simpleActionPerformed
        int w = pic1.getWidth() , h = pic1.getHeight() , c;
        pic2.setSize(2*w, 2*h);
        for( int y=0; y<h ; y++ )
        {   for( int x=0 ; x<w ; x++ )
            {   c=pic1.getPixel(x, y);            
                pic2.setPixel(2*x, 2*y, c);
                pic2.setPixel(2*x, 2*y+1, c);
                pic2.setPixel(2*x+1, 2*y, c);
                pic2.setPixel(2*x+1, 2*y+1, c);
            }
        }
    }//GEN-LAST:event_jMenuItem_Ampliacion_Al_Doble_simpleActionPerformed

    private void jMenuItem_Ampliacion_A_Cualquier_FactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Ampliacion_A_Cualquier_FactorActionPerformed
        int F=Integer.parseInt(JOptionPane.showInputDialog(this,"INGRESE UN NUMERO ENTERO"));
        int w = pic1.getWidth() , h = pic1.getHeight() , c;
        pic2.setSize(F*w, F*h);
        for( int y=0; y<h ; y++ )
        {   for( int x=0 ; x<w ; x++ )
            {   c=pic1.getPixel(x, y);            
                for( int i=0 ; i<F ; i++ )
                {   for( int j=0 ; j<F ; j++)                    
                        pic2.setPixel(F*x+i, F*y+j, c);                    
                }                
            }
        }
    }//GEN-LAST:event_jMenuItem_Ampliacion_A_Cualquier_FactorActionPerformed

    private void jMenuItem_Reduccion_A_La_Mitad_SimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Reduccion_A_La_Mitad_SimpleActionPerformed
        int w = pic1.getWidth() , h = pic1.getHeight() , c;
        pic2.setSize(w/2, h/2);
        for( int y=0; y<h/2 ; y++ )
        {   for( int x=0 ; x<w/2 ; x++ )
            {   c=pic1.getPixel(2*x, 2*y);            
                pic2.setPixel(x, y, c);
            }
        }
    }//GEN-LAST:event_jMenuItem_Reduccion_A_La_Mitad_SimpleActionPerformed

    private void jMenuItem_Reduccion_A_Cualquier_FactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Reduccion_A_Cualquier_FactorActionPerformed
        int F=Integer.parseInt(JOptionPane.showInputDialog(this,"INGRESE UN NUMERO ENTERO"));
        int w = pic1.getWidth() , h = pic1.getHeight() , c;
        pic2.setSize(w/F, h/F);
        for( int y=0; y<h/F ; y++ )
        {   for( int x=0 ; x<w/F ; x++ )
            {   c=pic1.getPixel(F*x, F*y);            
                pic2.setPixel(x, y, c);
            }
        }
    }//GEN-LAST:event_jMenuItem_Reduccion_A_Cualquier_FactorActionPerformed

    private void jMenuItem_Ampliacion_Al_Doble_Con_PromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Ampliacion_Al_Doble_Con_PromedioActionPerformed
        ampliacion_2X_Promedio3();
    }//GEN-LAST:event_jMenuItem_Ampliacion_Al_Doble_Con_PromedioActionPerformed

    void ampliacion_2X_Promedio3()
    {   int w = pic1.getWidth() , h = pic1.getHeight() , c1=0, c2=0, c3=0, c4=0;
        int r1, v1, a1, r2, v2, a2, r3, v3, a3, r4, v4, a4;
        pic2.setSize(2*w, 2*h);
        
        for( int y=0; y<h ; y++ )
        {   for( int x=0 ; x<w ; x++ )
            {   if( (x<w-1) && (y<h-1) )
                {   c1=pic1.getPixel(x, y);   
                    c2=pic1.getPixel(x+1, y); 
                    c3=pic1.getPixel(x+1, y+1);
                    c4=pic1.getPixel(x, y+1);                    
                }
                if( (x==w-1) && (y<h-1) )
                {   c1=c2=c3=pic1.getPixel(x, y);    
                    c4=pic1.getPixel(x, y+1);                       
                }
                if( (y==h-1) && (x<w-1) )
                {   c1=c3=c4=pic1.getPixel(x, y);    
                    c2=pic1.getPixel(x+1, y); 
                }
                if( (y==h-1) && (x==w-1) )
                {   c1=c2=c3=pic1.getPixel(x, y);    
                }
                
                r1=(c1 & 0xFF0000)>>16; v1=(c1 & 0xFF00)>>8;    a1=c1 & 0xFF; 
                r2=(c2 & 0xFF0000)>>16; v2=(c2 & 0xFF00)>>8;    a2=c2 & 0xFF;
                r3=(c3 & 0xFF0000)>>16; v3=(c3 & 0xFF00)>>8;    a3=c3 & 0xFF;
                r4=(c4 & 0xFF0000)>>16; v4=(c4 & 0xFF00)>>8;    a4=c4 & 0xFF;
                
                c2= ( (r1+r2)/2 )<<16 | ( (v1+v2)/2 )<<8 | ( (a1+a2)/2 );
                c3= ( (r1+r3)/2 )<<16 | ( (v1+v3)/2 )<<8 | ( (a1+a3)/2 );
                c4= ( (r1+r4)/2 )<<16 | ( (v1+v4)/2 )<<8 | ( (a1+a4)/2 );                
                                
                pic2.setPixel(2*x, 2*y, c1);
                pic2.setPixel(2*x+1, 2*y, c2);
                pic2.setPixel(2*x+1, 2*y+1, c3);
                pic2.setPixel(2*x, 2*y+1, c4);           
            }            
        }
    }
    
    void ampliacion_2X_Promedio2()
    {   int w = pic1.getWidth() , h = pic1.getHeight() , c1=0, c2=0, c3=0, c4=0;
        int x=0, y=0, r1, v1, a1, r2, v2, a2, r3, v3, a3, r4, v4, a4;
//        System.out.println(w+" "+h);
        pic2.setSize(2*w, 2*h);
        
        for( y=0; y<h-1 ; y++ )
        {   for( x=0 ; x<w-1 ; x++ )
            {   c1=pic1.getPixel(x, y); 
                    r1=(c1 & 0xFF0000)>>16;
                    v1=(c1 & 0xFF00)>>8;
                    a1=c1 & 0xFF; 
                c2=pic1.getPixel(x+1, y); 
                    r2=(c2 & 0xFF0000)>>16;
                    v2=(c2 & 0xFF00)>>8;
                    a2=c2 & 0xFF;
                c3=pic1.getPixel(x+1, y+1); 
                    r3=(c3 & 0xFF0000)>>16;
                    v3=(c3 & 0xFF00)>>8;
                    a3=c3 & 0xFF;
                c4=pic1.getPixel(x, y+1); 
                    r4=(c4 & 0xFF0000)>>16;
                    v4=(c4 & 0xFF00)>>8;
                    a4=c4 & 0xFF;  

                pic2.setPixel(2*x, 2*y, c1);                
                c2= ( (r1+r2)/2 )<<16 | ( (v1+v2)/2 )<<8 | ( (a1+a2)/2 );
                pic2.setPixel(2*x+1, 2*y, c2);                
                c3= ( (r1+r3)/2 )<<16 | ( (v1+v3)/2 )<<8 | ( (a1+a3)/2 );
                pic2.setPixel(2*x+1, 2*y+1, c3);                
                c4= ( (r1+r4)/2 )<<16 | ( (v1+v4)/2 )<<8 | ( (a1+a4)/2 );
                pic2.setPixel(2*x, 2*y+1, c4);
                if(x==w-2)
                {   x++;
                    c1=pic1.getPixel(x, y); 
                            r1=(c1 & 0xFF0000)>>16;
                            v1=(c1 & 0xFF00)>>8;
                            a1=c1 & 0xFF;
                    pic2.setPixel(2*x, 2*y, c1); 
                    pic2.setPixel(2*x+1, 2*y, c1);  
                    pic2.setPixel(2*x+1, 2*y+1, c1);
                    c4=pic1.getPixel(x, y+1); 
                        r4=(c4 & 0xFF0000)>>16;
                        v4=(c4 & 0xFF00)>>8;
                        a4=c4 & 0xFF;  
                    c4= ( (r1+r4)/2 )<<16 | ( (v1+v4)/2 )<<8 | ( (a1+a4)/2 );
                    pic2.setPixel(2*x, 2*y+1, c4); 
                    x--;
                }
                if(y==h-2)
                {   y++;
                    pic2.setPixel(2*x, 2*y, c1);
                    c1=pic1.getPixel(x, y); 
                        r1=(c1 & 0xFF0000)>>16;
                        v1=(c1 & 0xFF00)>>8;
                        a1=c1 & 0xFF;
                    c2=pic1.getPixel(x+1, y); 
                        r2=(c2 & 0xFF0000)>>16;
                        v2=(c2 & 0xFF00)>>8;
                        a2=c2 & 0xFF;  
                    c2= ( (r1+r2)/2 )<<16 | ( (v1+v2)/2 )<<8 | ( (a1+a2)/2 );                 
                    pic2.setPixel(2*x+1, 2*y, c2);  
                    pic2.setPixel(2*x+1, 2*y+1, c1);                
                    pic2.setPixel(2*x, 2*y+1, c1);   
                    y--;
                }
            }            
        }
    }
    
    void ampliacion_2X_Promedio()
    {   int w = pic1.getWidth() , h = pic1.getHeight() , c1, c2, c3, c4;
        int r1, v1, a1, r2, v2, a2, r3, v3, a3, r4, v4, a4;
        pic2.setSize(2*w, 2*h);

        for( int y=0; y<h-1 ; y++ )
        {   for( int x=0 ; x<w-1 ; x++ )
            {   c1=pic1.getPixel(x, y); 
                    r1=(c1 & 0xFF0000)>>16;
                    v1=(c1 & 0xFF00)>>8;
                    a1=c1 & 0xFF; 
                c2=pic1.getPixel(x+1, y); 
                    r2=(c2 & 0xFF0000)>>16;
                    v2=(c2 & 0xFF00)>>8;
                    a2=c2 & 0xFF;
                c3=pic1.getPixel(x+1, y+1); 
                    r3=(c3 & 0xFF0000)>>16;
                    v3=(c3 & 0xFF00)>>8;
                    a3=c3 & 0xFF;
                c4=pic1.getPixel(x, y+1); 
                    r4=(c4 & 0xFF0000)>>16;
                    v4=(c4 & 0xFF00)>>8;
                    a4=c4 & 0xFF;  
                    
                pic2.setPixel(2*x, 2*y, c1);                
                c2= ( (r1+r2)/2 )<<16 | ( (v1+v2)/2 )<<8 | ( (a1+a2)/2 );
                pic2.setPixel(2*x+1, 2*y, c2);                
                c3= ( (r1+r3)/2 )<<16 | ( (v1+v3)/2 )<<8 | ( (a1+a3)/2 );
                pic2.setPixel(2*x+1, 2*y+1, c3);                
                c4= ( (r1+r4)/2 )<<16 | ( (v1+v4)/2 )<<8 | ( (a1+a4)/2 );
                pic2.setPixel(2*x, 2*y+1, c4); 
            }
        }                
    }
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int w=pic1.getWidth(), h=pic1.getHeight(), c;
        pic2.setSize(w, h);
        for(int y=0;y<h;y++)
        {   for(int x=0;x<w;x++)
            {   c=pic1.getPixel(x, y);
                pic2.setPixel(x, y, c);
            }
        }
        pic2.repaint();   
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int w=pic1.getWidth(), h=pic1.getHeight();
        pic2.setSize(w, h);
        for(int y=0;y<h;y++)
        {   for(int x=0;x<w;x++)
            {   int c=pic1.getPixel(x, y); 
                
                int r=(c & 0xFF0000)>>16;
                int v=(c & 0xFF00)>>8;
                int a=c & 0xFF;
                
                int k=(int)(0.3*r+0.59*v+0.11*a);
                
                c=0xFF0000 | k<<16 | k<<8 | k;
                
                pic2.setPixel(x, y, c);
            }
        }
        pic2.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        setBrillo(jSlider1.getValue());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        setBrillo(jSlider1.getValue());
    }//GEN-LAST:event_jSlider1MouseDragged

    private void jSlider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseClicked
        jLabel1.setText(""+jSlider1.getValue());
    }//GEN-LAST:event_jSlider1MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if( !(jInternalFrame3.isVisible()) )
            jInternalFrame3.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTextField1.getText().length()==0||jTextField2.getText().length()==0)
            JOptionPane.showMessageDialog(this, "PORFAVOR INGRESE CONTRASTE Y ALFA");
        else
            setContraste(Integer.parseInt(jTextField1.getText()), Integer.parseInt(jTextField2.getText()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int w=pic1.getWidth(), h=pic1.getHeight();
        pic2.setSize(w, h);
        for(int y=0;y<h;y++){
            for(int x=0;x<w;x++){
                
                int c=pic1.getPixel(x, y);
                
                int r=(c & 0xFF0000)>>16;
                int v=(c & 0xFF00)>>8;
                int a=c & 0xFF;
                
                int nr=255-r;
                int nv=255-v;
                int na=255-a;
                
                c=0xFF0000 | nr<<16 | nv<<8 | na;
                pic2.setPixel(x, y, c);
            }
        }
        pic2.repaint();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void setContraste(int punto, int alfa)
    {   int w=pic1.getWidth(), h=pic1.getHeight(),k,r,v,a;
        pic2.setSize(w, h);
        double ang=alfa*Math.PI/180.0;
        Color c;
        for(int y=0;y<h;y++){
            for(int x=0;x<w;x++){
                c=new Color(pic1.getPixel(x, y));
                
                 r=c.getRed()-punto;    r=(int)(r*Math.tan(ang))+punto;
                 v=c.getGreen()-punto;    v=(int)(v*Math.tan(ang))+punto;
                 a=c.getBlue()-punto;    a=(int)(a*Math.tan(ang))+punto;
               
                if(r<0) r=0;    if(r>255)   r=255;
                if(v<0) v=0;    if(v>255)   v=255;
                if(a<0) a=0;    if(a>255)   a=255;
                
                k= r<<16 | v<<8 | a;
                pic2.setPixel(x, y, k);
            }
        }
        pic2.repaint();   
    }
    
    private void setBrillo(int brillo)
    {   int w=pic1.getWidth(), h=pic1.getHeight(),k,r,v,a;
        jLabel1.setText(""+jSlider1.getValue());
        pic2.setSize(w, h);
        for(int y=0;y<h;y++){
            for(int x=0;x<w;x++){
                
                 k=pic1.getPixel(x, y);
                
                 r=((k & 0xFF0000)>>16) + brillo;
                 v=((k & 0xFF00)>>8) + brillo;
                 a=(k & 0xFF) + brillo;
               
                if(r<0) r=0;    if(r>255)   r=255;
                if(v<0) v=0;    if(v>255)   v=255;
                if(a<0) a=0;    if(a>255)   a=255;
                
                k= r<<16 | v<<8 | a;
                
                pic2.setPixel(x, y, k);
            }
        }
        pic2.repaint();   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI_TDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI_TDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI_TDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI_TDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI_TDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem_Ampliacion_A_Cualquier_Factor;
    private javax.swing.JMenuItem jMenuItem_Ampliacion_Al_Doble_Con_Promedio;
    private javax.swing.JMenuItem jMenuItem_Ampliacion_Al_Doble_simple;
    private javax.swing.JMenuItem jMenuItem_Reduccion_A_Cualquier_Factor;
    private javax.swing.JMenuItem jMenuItem_Reduccion_A_La_Mitad_Simple;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private PanelImage pic1;
    private PanelImage pic2;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
